[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
dynamic_padding = true

title = ""
dynamic_title = false
decorations_theme_variant = "Dark"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
