modmap:
  - name: CapsLock to Ctrl
    device:
      only: ["AT Translated Set 2 keyboard"]
    remap:
      CAPSLOCK:
        held: LEFTCTRL
        alone: KEY_ESC
        alone_timeout_millis: 200
      ESC: CAPSLOCK

  - name: RightAlt to F16
    device:
      only: ["AT Translated Set 2 keyboard", "Corne Keyboard", "TOTEM Keyboard"]
    remap:
      KEY_RIGHTALT: KEY_F16
