modmap:
  - name: CapsLock to Ctrl
    device:
      only: ["AT Translated Set 2 keyboard"]
    remap:
      CAPSLOCK:
        held: LEFTCTRL
        alone: ESC
        alone_timeout_millis: 200

  - name: RightAlt to F16
    remap:
      KEY_RIGHTALT: KEY_F16
