local ls = require('luasnip')
local s = ls.snippet
local i = ls.insert_node
local fmt = require('luasnip.extras.fmt').fmt
local rep = require('luasnip.extras').rep

return {
  s(
    'react',
    fmt(
      [[
      import React, {{ Component }} from "react";

      class {} extends Component {{
        componentDidMount() {{
          {}
        }}

        render() {{
          return <div>{}</div>;
        }}
      }}

      export default {};
      ]],
      {
        i(1, 'component'),
        i(2, '// auto-generated by luasnip'),
        i(0, 'Hello, world'),
        rep(1),
      }
    )
  ),
}
