general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeouit = 60
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight
    on-resume = brightnessctl -rd rgb:kbd_backlight        # restore backlight
}

listener {
    timeout = 290                       # 4 min 50 sec
    on-timeout = brightnessctl -s set 5 # brightness to 5
    on-resume = brightnessctl -r        # restore brightness
}

listener {
    timeout = 300                       # 5 min
    on-timeout = login lock-session
}

listener {
    timeout = 600                       # 10 min
    on-timeout = systemctl suspend      # suspend pc
}
