[general]
import = [ "~/.config/alacritty/tokyo-night-storm.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono"
bold.style = "Bold"
size = 16
